#!/usr/bin/env perl

use v5.16;
use Net::OpenSSH;
use File::HomeDir;
use YAML qw(LoadFile);
use Scalar::Util qw(looks_like_number);

my $cf = File::HomeDir->my_home . q[/.kungfurc];
my $config = eval {
    LoadFile($cf);
};
die "$@" if $@;

foreach (qw/host user dir/) {
    die "Missing config parameter $_: $!" unless defined $_;
}

my $host = $config->{host};
my $dir  = $config->{dir};
delete $config->{$_} foreach qw/host dir/;

my $ssh = Net::OpenSSH->new($host,%{$config});

$ssh->error and
    die "Couldn't establish SSH connection: " . $ssh->error;

my @files = $ssh->capture(q[ls /home/kungfu/Downloads]);
map { chomp } @files;
say "$_ ) $files[$_]" foreach (0..$#files);
say;
print q[Enter the file you wish to download: ];

my $which = <STDIN>;
exit(1) unless $which ne '';
chomp $which;

warn "Not a number: $which$!" and exit(1)
    unless looks_like_number($which);
warn "Out of range: $which$!" and exit(1)
    unless $which > 0 and $which < scalar(@files);

my $downloaded = $ssh->scp_get({
        recursive => 1,
        verbose   => 1,
    },
    qq[/home/kungfu/Downloads/$files[0+$which]]);

say "Download completed successfully" if $downloaded;

exit(0);
